<h2>Dessin porte-bonheur</h2>
<p>Vous gardez le dessin de l'enfant. L'avion se stabilise mystérieusement.<br>
Romain, surprise :<br>
"Les turbulences ont disparu... C'est comme si on avait de la chance."<br>
La tour vous contacte :<br>
"LYN42, atterrissez à Gérone, piste 10."</p>

<div class="choix">
    <a href="index.php?choice=victoire" class="btn">Suivre les instructions</a>
    <a href="index.php?choice=32" class="btn">Demander une confirmation</a>
</div>