<h2>Cabine sous contrôle</h2>
<p>Le médecin calme les passagers. Romain vous informe :<br>"La tour nous guide vers Barcelone. Mais un orage se forme sur la route."<br>
Le médecin revient :<br>"Le passager malade a besoin d'oxygène rapidement."</p>

<div class="choix">
    <a href="index.php?choice=12" class="btn">Traverser l'orage pour gagner du temps</a>
    <a href="index.php?choice=13" class="btn">Contourner l'orage </a>
    <a href="index.php?choice=24" class="btn">Demander une priorité médicale à la tour</a>
</div>