<h2>Rassurer le couple</h2>
<p>Vous vous penchez vers le couple, près de la porte du cockpit :<br>
"Tout va bien, On est en sécurité."<br>
Romain vous rappelle à l'ordre :<br>
"On perd de l'altitude ! 28 000 pieds..."<br>
Un steward vous tend un dessin d'un enfant :<br>
"Il veut que vous le gardiez pour porter bonheur."</p>

<div class="choix">
    <a href="index.php?choice=4" class="btn">Rependre les commandes et stabiliser l'avion</a>
    <a href="index.php?choice=27" class="btn">Garder le dessin et continuer la descente</a>
</div>