<h2>Plongée manuelle</h2>
<p>Vous plongez à 3 000 pieds/minute. L'avion répond difficilement. Romain :<br>"On a évité l'autre avion, mais on est maintenant à 25 000 pieds sans autorisation !"<br>La tour de Barcelone répond enfin :<br>"IBR42, ici Barcelone. Descendez à 10 000 pieds, piste 25 libre pour atterrissage d'urgence."
</p>

<div class="choix">
    <a href="index.php?choice=10" class="btn">Suivre les instructions de la tour</a>
    <a href="index.php?choice=11" class="btn">Demander une confirmation visuelle</a>
</div>