<h2>Priorité médicale</h2>
<p>Vous demandez une priorité médicale. La tour répond :<br>
"Priorité accordée. Atterrissage à Barcelone dans 15 minutes."<br>
Le médecin revient :<br>
"Le passager a besoin d'un respirateur. On n'en a pas à bord."</p>

<div class="choix">
    <a href="index.php?choice=victoire" class="btn">Atterrir en urgence</a>
    <a href="index.php?choice=29" class="btn">Demander un transfert médical à l'atterissage</a>
</div>