<h2>Silence radio</h2>
<p>Vous appelez la tour de Barcelone : <br>"Barcelone, ici IBR42, alerte TCAS ! Confirmez !"<br>
Pas de réponse.<br>Le copilote affolée :<br>"L'autre avion ne bouge pas ! On a 10 secondes avant l'impact !"</p>

<div class="choix">
    <form action="index.php" method="get">
        <button type="submit" name="choice" value="6" class="btn">Plonger manuellement</button>
    </form>
    <form action="index.php" method="get">
        <button type="submit" name="choice" value="bad-end" class="btn">Attendre une réponse </button>
    </form>
</div>