<h2>Réparation du train</h2>
<p>Vous tentez une dernière réparation. Le train se déploie enfin !<br>
Mais la tour annonce un nouvel obstacle :<br>
"Un camion de pompiers bloque la piste."</p>

<div class="choix">
    <a href="index.php?choice=victoire" class="btn">Atterrir malgré le camion</a>
    <a href="index.php?choice=bad-end" class="btn">Faire un tour pour attendre</a>
    <a href="index.php?choice=" class="btn">A faire</a>
</div>