<h2>Attention ça descend</h2>
<p>L'avion plonge à 2 500 pieds/minute. Les passagers hurlent, les masques à oxygène tombent.
Claire, tendue :<br>
"On descend trop vite ! Les passagers vont paniquer !"<br>Une nouvelle alerte :<br>"SINK RATE ! PULL UP !"<br>Un couple, près du cockpit pleure près du cockpit :<br>
"Tient toi à moi, on va surement atterir dans pas très longtemps"</p>

<div class="choix">
    <form action="index.php" method="get">
        <button type="submit" name="choice" value="4" class="btn">Réduire la descente pour stabiliser l'avion</button>
    </form>
    <form action="index.php" method="get">
        <button type="submit" name="choice" value="5" class="btn">Continuer la descente malgré les risques</button>
    </form>
    <form action="index.php" method="get">
        <button type="submit" name="choice" value="22" class="btn">Donner des indications sur le vol au couple avant de stabiliser l'avion</button>
    </form>
</div>