<h2>Extincteurs en action</h2>
<p>Vous activez les extincteurs. La fumée diminue, mais Romain crie : <br>
"Les extincteurs vident nos réserves d'oxygène ! On doit atterrir maintenant !"<br>
La tour confirme :<br>
"Piste libre, atterrissez."</p>

<div class="choix">
    <a href="index.php?choice=victoire" class="btn">Atterrir avec les extincteurs activés</a>
    <a href="index.php?choice=30" class="btn">Éteindre les extincteurs pour économiser l'oxygène</a>
</div>