    <h2>Silence radio</h2>
    <p>Vous appelez la tour de Barcelone : <br>"Barcelone, ici IBR42, alerte TCAS ! Confirmez !"<br>
    Pas de réponse.<br>Le copilote affolée :<br>"L'autre avion ne bouge pas ! On a 10 secondes avant l'impact !"<br>

    <div class="choix">
        <a href="index.php?choice=6" class="btn">Plonger manuellement</a>
        <a href="index.php?choice=bad-end" class="btn">Attendre une réponse </a>
    </div>