<h2>Confirmation visuelle</h2>
<p>Vous demandez une confirmation visuelle. La tour : <br>
"IBR42, l'aéroport est dégagé. Atterrissez immédiatement."<br>
Romain :<br>
"On a un problème avec les volets. Ils ne sortent qu'à moitié."</p>

<div class="choix">
    <a href="index.php?choice=20" class="btn">Atterrir avec les volets partiellement sortis</a>
    <a href="index.php?choice=bad-end" class="btn">Faire un tour pour tenter de les déployer</a>
</div>