<h2>Phares allumés</h2>
<p>Vous allumez les phares. Le jet privé réagit enfin et dévie sa trajectoire.<br>
"Il nous a vus !" s'exclame Romain. <br>
Mais l'avion tremble soudain :<br>
"On a perdu un panneau de l'aile gauche !"</p>

<div class="choix">
    <a href="index.php?choice=6" class="btn">Stabiliser l'avion et descendre</a>
    <a href="index.php?choice=31" class="btn">Déclarer une urgence absolue</a>
</div>