<h2>Passager en détresse</h2>
<p>Le médecin s'occupe du passager malade. Romain vous informe : <br>
"Il a une crise d'asthme sévère. On a besoin de descendre à 10 000 pieds pour qu'il respire mieux."<br>
La tour de Barcelone répond enfin :<br>
"LYN42, ici Barcelone. Atterrissez immédiatement, piste 25."</p>

<div class="choix">
    <a href="index.php?choice=28" class="btn">Descendre à 10 000 pieds pour le passager</a>
    <a href="index.php?choice=10" class="btn">Suivre les instructions de la tour</a>
</div>