<h2>Stabilisation réussie</h2>
<p>Vous réduisez la descente. L'avion se stabilise à 30 000 pieds. Le copilote souffle :<br>
"On a évité la collision, mais on a perdu le contact avec la tour."<br>Un passager, un médecin, se présente :<br>
"Je peux aider à calmer les passagers !"<br>Un steward vous murmure : <br>
"Un passager a fait un malaise à l'arrière... Il respire mal."</p>

<div class="choix">
    <a href="index.php?choice=7" class="btn">Lui confier la gestion de la cabine</a>
    <a href="index.php?choice=8" class="btn">Rester concentré sur le pilotage</a>
    <a href="index.php?choice=23" class="btn">Envoyer le médecin s'occuper du passager malade</a>
</div>