<h2>Descente forcée</h2>
<p>Vous continuez à descendre. L'avion tremble, les passagers sont en panique. Le copilote nomé Romain crie :<br>
"On dépasse la vitesse maximale ! L'aile gauche vibre !"<br>Soudain, un BANG retentit.</p>

<div class="choix">
    <a href="index.php?choice=9" class="btn">Remonter immédiatement</a>
    <a href="index.php?choice=bad-end" class="btn">Maintenir la descente</a>
</div>