<h2>Visualisation de l'intrus</h2>
<p>Vous regardez par le hublot. Romain ajuste les lumières du cockpit pour mieux voir. Une silhouette noire se profile à tribord, sans feux de position.<br>
"C'est un jet privé... Il ne répond pas aux radars !"<br>
L'alerte TCAS se fait plus pressante :<br>
"DESCEND ! DESCEND NOW !"</p>

<div class="choix">
    <a href="index.php?choice=2" class="btn">Plonger immédiatement</a>
    <a href="index.php?choice=26" class="btn">Allumer les phares de l'avion pour signaler votre présence</a>
</div>