<h2>A modifier</h2>
<p>Vous éteignez les extincteurs. La fumée réapparaît, mais l'oxygène est préservé. Romain dit :<br>
"On peut tenir jusqu'à Barcelone, mais la visibilité baisse."
Un passager crie :
"Il y a des flammes près des toilettes !"</p>

<div class="choix">
    <a href="index.php?choice=victoire" class="btn">Atterir en urgence</a>
    <a href="index.php?choice=bad-end" class="btn">Utiliser les extincteurs restants</a>
</div>